services:
  - type: web
    name: spam-detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app --bind 0.0.0.0:$PORT --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
